sources:
  - name: "nine.com.au"
    module: "nine_com_au"
    base_url: "https://www.nine.com.au"
    front_pages:
      - slug: "home"
        path: "/"
      - slug: "australia-news"
        path: "/australia-news"
      - slug: "world-news"
        path: "/world-news"
      - slug: "business-news"
        path: "/business-news"
      - slug: "sport"
        path: "/sport"
      - slug: "entertainment"
        path: "/entertainment"
      - slug: "lifestyle"
        path: "/lifestyle"
  - name: "ABC News"
    module: "abc_net_au"
    base_url: "https://www.abc.net.au"
    front_pages:
      - slug: "home"
        path: "/"
